/* Copyright (c) 2013-2015, The Linux Foundation. All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimer.
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimer in the documentation and/or other materials provided
 *       with the distribution.
 *     * Neither the name of The Linux Foundation nor the names of its
 *       contributors may be used to endorse or promote products derived
 *       from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED
 * WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT
 * ARE DISCLAIMED.  IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS
 * BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR
 * BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
 * WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
 * OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN
 * IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 */

/*---------------------------------------------------------------------------
 * This file is autogenerated file using gcdb parser. Please do not edit it.
 * Update input XML file to add a new entry or update variable in this file
 * VERSION = "1.0"
 *---------------------------------------------------------------------------*/

#ifndef _PANEL_JD35695_1080P_CMD_H_
#define _PANEL_JD35695_1080P_CMD_H_
/*---------------------------------------------------------------------------*/
/* HEADER files                                                              */
/*---------------------------------------------------------------------------*/
#include "panel.h"

/*---------------------------------------------------------------------------*/
/* Panel configuration                                                       */
/*---------------------------------------------------------------------------*/
static struct panel_config jd35695_1080p_cmd_panel_data = {
	"qcom,mdss_dsi_jd35695_1080p_cmd", "dsi:0:", "qcom,mdss-dsi-panel",
	10, 1, "DISPLAY_1", 0, 0, 60, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel resolution                                                          */
/*---------------------------------------------------------------------------*/
static struct panel_resolution jd35695_1080p_cmd_panel_res = {
  1080, 1920, 100, 82, 8, 0, 3, 7, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel color information                                                   */
/*---------------------------------------------------------------------------*/
static struct color_info jd35695_1080p_cmd_color = {
  24, 0, 0x0000ff, 0, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Panel on/off command information                                          */
/*---------------------------------------------------------------------------*/
static char jd35695_1080p_cmd_on_cmd0[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd1[] = {
	0x35, 0x00, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd2[] = {
	0x05, 0x00, 0x39, 0xC0,
	0x2a, 0x00, 0x00, 0x04,
	0x37, 0xFF, 0xFF, 0xFF,
};

static char jd35695_1080p_cmd_on_cmd3[] = {
	0x05, 0x00, 0x39, 0xC0,
	0x2b, 0x00, 0x00, 0x07,
	0x7f, 0xFF, 0xFF, 0xFF,
};

static char jd35695_1080p_cmd_on_cmd4[] = {
	0x03, 0x00, 0x29, 0xC0,
	0x44, 0x05, 0x00, 0xFF,
};

static char jd35695_1080p_cmd_on_cmd5[] = {
	0xFF, 0xE0, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd6[] = {
	0xB5, 0x86, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd7[] = {
	0xB6, 0x77, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd8[] = {
	0xB8, 0xAD, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd9[] = {
	0xFB, 0x01, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd10[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd11[] = {
	0x36, 0x03, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd12[] = {
	0xFF, 0x23, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd13[] = {
	0x08, 0x03, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd14[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd15[] = {
	0x51, 0xFF, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd16[] = {
	0x53, 0x2C, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd17[] = {
	0x55, 0x02, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd18[] = {
	0xFF, 0x23, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd19[] = {
	0xFB, 0x01, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd20[] = {
	0x05, 0x24, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd21[] = {
	0x01, 0x84, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd22[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char jd35695_1080p_cmd_on_cmd23[] = {
	0x11, 0x00, 0x05, 0x80
};

static char jd35695_1080p_cmd_on_cmd24[] = {
	0x29, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd35695_1080p_cmd_on_command[] = {
	{0x4, jd35695_1080p_cmd_on_cmd0, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd1, 0x00},
	{0xc, jd35695_1080p_cmd_on_cmd2, 0x00},
	{0xc, jd35695_1080p_cmd_on_cmd3, 0x00},
	{0x8, jd35695_1080p_cmd_on_cmd4, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd5, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd6, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd7, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd8, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd9, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd10, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd11, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd12, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd13, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd14, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd15, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd16, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd17, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd18, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd19, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd20, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd21, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd22, 0x00},
	{0x4, jd35695_1080p_cmd_on_cmd23, 0x64},
	{0x4, jd35695_1080p_cmd_on_cmd24, 0x11}
};

#define JD35695_1080P_CMD_ON_COMMAND 25


static char jd35695_1080p_cmdoff_cmd0[] = {
	0xFF, 0x10, 0x15, 0x80
};

static char jd35695_1080p_cmdoff_cmd1[] = {
	0x53, 0x00, 0x15, 0x80
};

static char jd35695_1080p_cmdoff_cmd2[] = {
	0x28, 0x00, 0x05, 0x80
};

static char jd35695_1080p_cmdoff_cmd3[] = {
	0x10, 0x00, 0x05, 0x80
};

static struct mipi_dsi_cmd jd35695_1080p_cmd_off_command[] = {
	{0x4, jd35695_1080p_cmdoff_cmd0, 0x00},
	{0x4, jd35695_1080p_cmdoff_cmd1, 0x00},
	{0x4, jd35695_1080p_cmdoff_cmd2, 0x11},
	{0x4, jd35695_1080p_cmdoff_cmd3, 0x32}
};

#define JD35695_1080P_CMD_OFF_COMMAND 4


static struct command_state jd35695_1080p_cmd_state = {
  0, 1
};

/*---------------------------------------------------------------------------*/
/* Command mode panel information                                            */
/*---------------------------------------------------------------------------*/
static struct commandpanel_info jd35695_1080p_cmd_command_panel = {
  1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0
};

/*---------------------------------------------------------------------------*/
/* Video mode panel information                                              */
/*---------------------------------------------------------------------------*/
static struct videopanel_info jd35695_1080p_cmd_video_panel = {
  1, 0, 0, 0, 1, 1, 2, 0, 0x9
};

/*---------------------------------------------------------------------------*/
/* Lane configuration                                                        */
/*---------------------------------------------------------------------------*/
static struct lane_configuration jd35695_1080p_cmd_lane_config = {
  4, 0, 1, 1, 1, 1, 0
};

/*---------------------------------------------------------------------------*/
/* Panel timing                                                              */
/*---------------------------------------------------------------------------*/
static const uint32_t jd35695_1080p_cmd_timings[] = {
  0xE7, 0x43, 0x37, 0x00, 0x60, 0x6C, 0x39, 0x45, 0x5b, 0x03, 0x04, 0x00
};

static struct panel_timing jd35695_1080p_cmd_timing_info = {
  0, 4, 0x20, 0x3e
};

/*---------------------------------------------------------------------------*/
/* Panel reset sequence                                                      */
/*---------------------------------------------------------------------------*/
static struct panel_reset_sequence jd35695_1080p_cmd_panel_reset_seq = {
	{1, 0, 1, }, {11, 2, 12, }, 2
};

/*---------------------------------------------------------------------------*/
/* Backlight setting                                                         */
/*---------------------------------------------------------------------------*/
static struct backlight jd35695_1080p_cmd_backlight = {
  1, 1, 4095, 100, 1, "PMIC_8941"
};

#endif /*_PANEL_JD35695_1080P_CMD_H_*/